title = "JoPoWa-Vis Config"

description = "Configuration file for the Python visualisation of the Power Water System"

[headings]
title = "JoPoWa-Vis"
sub-title = "Visualisation of the Jordan Power and Water System"

[profile_mapper]
PV = "pv"
Wind = "wind"
CSP = "csp"
Hydro = "hydro"
Demand = "demand"

[units]
energy = "GWh"
power = "MW"
water = "Mm3"

# colors will be used for plots. If not specified colors from oemof.tabular
# will be used as default values for technologies and carriers ('gas', 'coal')
[colors]
geothermal= "darkred"
csp = "orange"
other = "gray"
demand = "darkslateblue"
storage = "salmon"
excess = "firebrick"
coal = "dimgray"
shortage = "firebrick"
gas-gt = "gray"
gas-ccgt = "darkgray"
gas = "darkgray"
biogas = "darkseagreen"
biomass = "darkseagreen"

[paths]
profiles = "data/jordan-input-data/profile/energy-water-profile.csv"
